spring:
  profiles:
    active: @project.mode@
# CONFIGURACION DE LOS HTTP encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
# PARA LA INTERNALIZACION
  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8
# DEVTOOLS
  devtools:
    restart:
      additional-paths: .
    livereload:
      enabled: true
    restart:
      enabled: true
# PARA LA BD MONGODB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spielberg
# CONFIGURACION DE EUREKA

# CONFIGURACION ARCHIVO LOG
logging:
  path: C:/APP/Logs/ETMongo
  config: http://localhost:8888/ETMongo/default/master/ETMongoLogback.xml

# ACTUATOR
management:
  endpoints:
    enabled-by-default: true

# PROPERTIES CUSTOM
prefix-api: /api
